<?php

return array (

  'home'=>"Home",
  'dashboard'=>"Dashboard",
  'product'=>"Product",
  'pricing'=>"Pricing",
  'testimonials'=>"Testimonials",
  'faq'=>"FAQ",
  'login'=>"Login",
  'slogan_subtitle'=>"REQUEST A RIDE NOW",
  'slogan'=>"Request a ride now, via Whatsapp",
  'form_title'=>"Request a ride now",
  'form_input_start'=>"Enter pickup location",
  'form_input_end'=>"Enter destination",
  'form_input_phone'=>"Phone",
  'form_request'=>"Request now",
  'chat_now'=>"Order via Whatsapp",
  'confirmdialog_title'=>"Request a ride now",
  'to'=>"to",
  'i_agree_to' => 'I agree to the',
  'and'=>"and",
  'privacy_policy' => 'Privacy Policy',
  'terms_of_service' => 'Terms of Service',
  'product_title'=>"All the tools you need to grow",
  'product_subtitle'=>"We have heard the farmers needs. From seed to sell, we got you covered.",
  'pricing_title'=>"Pricing Plans",
  'pricing_subtitle'=>"Our plans were crafted specifically to help you succeed.",
  'start_now'=>"Start now",
  'testimonial_subtitle'=>"Why our customers love our product",
  "testimonial_info"=>"Don't just take our word for it, read from our extensive list of case studies and customer testimonials.",
  'fr_as_qu'=>"Frequently Asked Questions",
  'faq_subtitle'=>"Here are some of the most common frequently asked questions",
  "blog_title"=>"Finding a taxi hasn't been easier",
  "apps_title"=>"There’s more to love in the apps",
  "download_driver_app"=>"Download the driver app",
  "download_client_app"=>"Download the client app",
  "sign_up_to_drive"=>"Sign up to drive",
  "sign_up_drivers_slogan"=>"Socialize your taxi",
  "sign_up_drivers_slogan_description"=>"Become part of our ever growing community of taxi companies and individuals. Bring your taxis closer to the clients utilizing the WhatsApp platform.",
  "company_or_brand_name"=>"Company or brand name",
  "personal_name"=>"First and Last name",
  "signup"=>"Sign up",
  'view_pricing'=>"View pricing",
  'faq'=>"FAQ",
  'driver_found_nearby'=>"Driver found nearby",
  'drivers_found_nearby'=>"Drivers found nearby",
);
