<?php

return array (
  'featured_clients'=>"Featured clients",
  'list_of_featured_clients'=>"Here is a list of some of our clients",
  'Product' => 'Product',
  'and' => 'and',
  'dashboard' => 'Dashboard',
  'demo' => 'Demo',
  'demo_badge' => 'Demo',
  'demo_description' => 'Scan the QR code to open the menu on your phone. You don\'t need an app. Make an order and send it on our demo WhatsApp. No, we will not deliver it to you :)',
  'demo_image' => 'You can scan it with your phone camera. No App required.',
  'demo_title' => 'Experience the ordering process',
  'editor1' => 'Your 1st order is minutes away',
  'editor2' => 'Ordering on WhatsApp Supercharged!',
  'editor3' => 'Leverage WhatsApp as a platform to accept orders. Create a digital menu for your Restaurant or Bar. Share with your clients and let them order via Mobile',
  'explain_mainsubtitle' => 'Ordering is easy as chatting with a friend',
  'explain_maintitle' => 'There is no simpler process',
  'feature_main_subtitle1' => 'Accept payments via PayPal, Klarna, iDeal, Apple Pay and 20 more.',
  'feature_main_subtitle2' => 'You are able to connect third-party ordering bot to automate
  the process',
  'features' => 'Features',
  'footer_subtitle' => 'Ordering on WhatsApp Supercharged!',
  'footer_title' => 'WhatsApp Ordering!',
  'hero_badge' => 'Contact-less QR code menu now avaialbe',
  'hero_badge_type' => 'HOT',
  'hero_description' => 'Leverage WhatsApp as platform to accept orders. Create a digital menu for
  your Restaurant or Bar. Share with your clients and let them order via Mobile',
  'hero_subtitle' => 'Ordering on WhatsApp Supercharged!',
  'hero_title' => 'User-friendly',
  'i_agree_to' => 'I agree to the',
  'join_now' => 'Join now',
  'login' => 'Login',
  'modal_input_email' => 'Your email',
  'modal_input_name' => 'Restaurant or bar name',
  'modal_input_phone' => 'Phone',
  'modal_title' => 'Register Your Restaurant',
  'month' => 'month',
  'pricing' => 'Pricing',
  'pricing_button' => 'Start with',
  'pricing_subtitle' => '14-day money back guarantee. Risk-free, you can cancel at anytime.',
  'pricing_title' => 'WhatsApp Ordering Pricing',
  'privacy_policy' => 'Privacy Policy',
  'product' => 'Product',
  'register' => 'Register',
  'see_demo' => 'See demo',
  'start_now' => 'Start now',
  'success' => 'Changed successfully. Please refresh the page!',
  'terms_of_service' => 'Terms of Service',
  'test_on_web' => 'Test it on web',
  'testimonials' => 'Testimonials',
  'testimonials_subtitle' => 'What our customers say',
  'testimonials_title' => 'Testimonials',
  'year' => 'year',
);
